#!/bin/bash
# Usage: ./migrate <GITOLITE_HOST> <$GITHUB_ORG> [hub create parameters...]
#

set -e

GITOLITE_HOST="$1"
GITHUB_ORG="$2"
shift 2

for repo in $(ssh "gitolite@$GITOLITE_HOST" 2> /dev/null | grep '^ R' | grep -v ' R W C ' | awk '{print $NF}' | sort); do
    echo "Moving $repo from $GITOLITE_HOST to $GITHUB_ORG/$repo"

    git clone "gitolite@$GITOLITE_HOST:$repo" "/tmp/g2g-$repo"

    cd "/tmp/g2g-$repo"

    git remote rename origin gitolite

    hub create "$@" "$GITHUB_ORG/$repo"
    git remote show origin

    git push -u origin $(for a in $(git branch --list --remote "gitolite/*" | grep -v --regexp='->'); do echo "$a:refs/heads${a//gitolite/}"; done)

    rm -Rf "/tmp/g2g-$repo"
done
